name: Build Docker Images

permissions:
  contents: read
  security-events: write

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit sha"
        required: true

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    # Usually, a successful job takes ~17 mins.
    # Anything more than 30 mins is a sign that job is stuck.
    # This is a workaround until we find the root cause.
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit || '' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: ${{ !env.ACT }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set SHA when dispatched
        run: |
          SHA=$([ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] && echo "${{ github.event.inputs.commit }}" || echo "${GITHUB_SHA}")
          echo "SHA=${SHA}" >> $GITHUB_ENV

      - name: Prepare build args
        id: build_args
        run: |
          github_sha_short=${SHA:0:7}
          echo "IMAGE_TAG=sha-${github_sha_short}" >> $GITHUB_ENV
          TEMPORAL_SHA=$(git submodule status -- temporal | awk '{print $1}')
          echo "TEMPORAL_SHA=${TEMPORAL_SHA}" >> $GITHUB_ENV
          TCTL_SHA=$(git submodule status -- tctl | awk '{print $1}')
          echo "TCTL_SHA=${TCTL_SHA}" >> $GITHUB_ENV
          TAG_LATEST=${{(github.event_name == 'push' && github.ref == 'refs/heads/main') && 'true' || 'false'}}
          echo "TAG_LATEST=${TAG_LATEST}" >> $GITHUB_ENV
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Prepare Go Build Cache for Docker
        uses: actions/cache@v3
        with:
          path: go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}

      - name: Inject go-build-cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v2.1.3
        with:
          cache-source: go-build-cache

      # You can't use `load` when building a multiarch image, so we build and load the
      # native image and build multiarch images later
      - name: Bake native images for security scanning
        uses: docker/bake-action@v4
        with:
          load: true
          set: |
            server.platform=linux/arm64
            admin-tools.platform=linux/arm64
            auto-setup.platform=linux/arm64

      - name: Bake and push multiarch images
        if: ${{ github.event_name == 'push' && !env.ACT }}
        uses: docker/bake-action@v4
        with:
          push: true

      - name: Ensure images work
        run: make IMAGE_TAG=${{env.IMAGE_TAG}} test
